services:
  - type: web
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    instances: 1
    ports:
      - 8080
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: dev
